# Generated by Django 4.2.26 on 2025-11-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainedmodels',
            options={'verbose_name': 'Trained Model', 'verbose_name_plural': 'Trained Models'},
        ),
    ]
